export const content = {
  meta: {
    title: 'Pixa - すべてのAIモデルをひとつに',
    description: '画像、動画、コード、文書生成、Webアプリのデバッグまで。AIの力をひとつのプラットフォームで。',
  },
  nav: {
    logo: 'Pixa',
    links: ['API', 'ブログ', 'ソリューション'],
    features: '機能',
    pricing: '料金',
    playground: 'プレイグラウンドを試す',
    dropdown: [
      ['bi-list-columns-reverse', 'プロンプトライブラリ', 'すぐ使えるプロンプトテンプレートを収録'],
      ['bi-grid-1x2-fill', '統合インターフェース', '複数のAIモデルをひとつの画面でテスト'],
      ['bi-globe', 'リアルタイムWeb検索', 'インターネットをリアルタイムに検索'],
      ['bi-image-fill', '画像生成', 'プロンプトから画像を生成'],
      ['bi-calendar-range', '履歴', '前回の会話の続きから再開'],
      ['bi-translate', '多言語対応', '複数の言語で自然に対話'],
    ],
  },
  hero: {
    headline1: 'すべてのAIモデルを',
    headline2: 'ひとつの場所に',
    subheadline: 'Pixaのインターフェースで、画像・動画・コード・文書の生成からWebアプリのデバッグまで。あなたのためのオールインワンAIコンパニオンです。',
    watchVideo: '動画を見る',
    getStarted: '今すぐ始める',
    signupPrompt: '会話を続けるにはサインアップしてください',
    userCount: '+20,000',
    userCountDesc: 'Benをはじめとする20,000人以上のPixaユーザーに加わりましょう',
    signUp: 'サインアップ',
    typedStrings: [
      'ルービックキューブの解き方をステップごとに教えて',
      'Pixaプレイグラウンドとは？',
      'AI SaaSアプリを作るには？',
      'Pixa APIを統合する方法は？',
    ],
    promptPlaceholder: 'SaaSアプリの作り方は？',
    tryPrompts: 'プロンプトを試す',
    aiModels: [
      { name: 'GPT 4o', logo: '/assets/images/brand-logos/openai.svg', alt: 'GPT 4o' },
      { name: 'Gemini', logo: '/assets/images/brand-logos/googlegemini.svg', alt: 'Gemini' },
      { name: 'Llama 3', logo: '/assets/images/brand-logos/meta.svg', alt: 'Llama 3' },
      { name: 'Claude', logo: '/assets/images/brand-logos/claude.svg', alt: 'Claude' },
    ],
    sidebar: [
      ['bi-image', '画像生成'],
      ['bi-file-pdf', 'PDF生成'],
      ['bi-code-square', 'コード生成'],
    ],
    showAll: 'すべて表示',
  },
  trustedBy: {
    heading: '世界中のブランドに信頼されています',
    logos: ['google', 'microsoft', 'adobe', 'airbnb', 'stripe', 'reddit'],
  },
  build: {
    heading: 'Pixa APIの上に',
    headingAccent: '独自のAIアプリを構築',
    desc: 'Pixaのプレイグラウンドは、最先端のLLM APIエンドポイントで動作しています。要約、テキスト生成、Q&A処理などの高度な機能を簡単に自動化できます。',
    cta: 'Pixa APIを確認する',
  },
  benefits: [
    { image: '/assets/images/home/api.png', title: '統合インターフェース', desc: 'お気に入りのチャットモデルをひとつのシームレスなプラットフォームに集約。複数のAIシステムを切り替える手間なく、一元管理できます。' },
    { image: '/assets/images/home/api.png', title: 'APIアクセス', desc: 'PixaのLLM APIは、高度な要約、テキスト生成、Q&A機能を提供。JSON、HTML、Markdown、プレーンテキストに対応します。' },
    { image: '/assets/images/home/integrations1.png', title: '事前構築済みツール', desc: '画像、動画、音楽、PDF生成など多彩なAI統合を提供。高度な機能をアプリへ簡単に組み込めます。' },
    { image: '/assets/images/home/ai-models.png', title: '複数のAIモデル', desc: 'ChatGPT、Gemini、Claude、Mistralなど多様なAIモデルをサポートし、言語・創作タスクを広く支援します。' },
  ],
  tools: [
    ['bi-code-square', 'AIコードジェネレーター', '自然言語やパターンからコードを生成し、開発を効率化します。'],
    ['bi-file-pdf-fill', 'PDF生成', 'PDF作成とコンテンツ抽出を自動化し、文書管理を改善します。'],
    ['bi-image-fill', '画像生成', 'テキストやパターンからビジュアルを作成し、デザイン作業を強化します。'],
    ['bi-bar-chart-line-fill', 'AI分析', 'データのパターンとトレンドを分析し、意思決定に役立つ洞察を提供します。'],
    ['bi-music-note-beamed', '音楽生成', '入力パラメータからオリジナル楽曲を生成します。'],
    ['bi-camera-video-fill', '動画生成', 'テキストやテンプレートから動画を生成し、制作を効率化します。'],
  ],
  features: [
    ['/assets/images/home/prompts2.png', 'プロンプトライブラリ', 'テンプレートを使ってワークフローをすばやく加速できます。'],
    ['/assets/images/home/search.png', 'リアルタイムWeb検索', 'AIチャットプレイグラウンド内でライブ検索結果を即座に取得できます。'],
    ['/assets/images/home/image.png', '画像生成', '複数モデルから即座に画像を生成し、説明文やテンプレートからビジュアルを作成します。'],
    ['/assets/images/home/history.png', '履歴', '以前のトピックを記憶しているので、いつでも会話を再開できます。'],
    ['/assets/images/home/import.png', 'コンテンツのインポート', 'PDF、画像、文書を簡単に取り込み、質問、抽出、要約に活用できます。'],
    ['/assets/images/home/multilingual.png', '多言語サポート', 'ChatGPTとGeminiは100以上の言語で理解し、応答できます。'],
  ],
  subscription: {
    heading: 'すべてがひとつのサブスクリプションで',
    desc: '複数の高額サブスクリプションに支払う必要はありません。ひとつのプランで複数のAIモデルにアクセスし、年間コストを大きく削減できます。',
    cta: 'チャットを始める',
  },
  testimonials: [
    ['man2.jpg', 'Mante', 'Glu, CTO', '複数のAIモデルにひとつの画面でアクセスできるようになり、チームの生産性が大きく向上しました。'],
    ['women.jpg', 'Trich B', 'AMI, CEO', 'Pixaを導入してから、コンテンツ制作のスピードが3倍になりました。'],
    ['man.jpg', 'John B', 'Benz, CEO', 'API統合がとてもシンプルで、自社アプリへの組み込みが数時間で完了しました。'],
    ['man2.jpg', 'Ben Alfert', 'XZ Tech, CTO', 'コスト削減と機能の充実度を考えると、Pixaは圧倒的な価値があります。'],
    ['women.jpg', 'Rachel', 'Gem, CTO', '多言語対応はグローバルビジネスに欠かせません。100以上の言語で自然に動作します。'],
    ['man.jpg', 'Jamie', 'SnapFist.ai, CEO', '画像生成ツールが使いやすく、マーケティング素材の制作時間を大幅に短縮できました。'],
  ],
  pricing: [
    { name: 'ベーシック', price: '¥0', desc: '日常使いに必要なAIツール', cta: '無料で始める', features: ['AIチャット1,000メッセージ', 'プレミアム画像生成30回', 'プレミアム音楽生成10回', '全プレミアムAIモデルへのアクセス', '新機能への早期アクセス'] },
    { name: 'プロ', price: '¥1,800', desc: 'パワーユーザー向けの高度な機能', cta: 'プロを始める', features: ['AIチャット5,000メッセージ', '画像生成100回', '音楽生成40回', '全プレミアムAIモデルへのアクセス', '優先サポート'] },
    { name: 'チーム', price: '¥4,400', desc: 'チームと企業向け', cta: 'チームを始める', features: ['AIチャット10,000メッセージ', '画像生成300回', '音楽生成100回', '管理者コントロール', 'チーム分析'] },
  ],
  articles: [
    ['/assets/images/home/article1.png', '機械学習', '2024年7月17日', '最新のAIツール'],
    ['/assets/images/home/article2.jpg', 'お知らせ', '2024年6月22日', 'Pixaの新技術を発表'],
    ['/assets/images/home/article3.png', 'お知らせ', '2024年4月27日', 'Pixaプレイグラウンドを公開'],
  ],
  faq: [
    ['Pixaプレイグラウンドとは？', 'Pixaプレイグラウンドは、GPT-4、Claude、Geminiなど複数のLLMモデルをシームレスに試せる統合Webアプリです。'],
    ['LLMとは何ですか？', 'LLMは大規模言語モデルのことで、大量のテキストデータで学習し、人間らしい文章の理解や生成を行うAIモデルです。'],
    ['どこで異なるAIモデルを試せますか？', 'PixaのAIプレイグラウンドで、GPT-4、Claude、Perplexityなど複数のモデルをテストできます。'],
    ['Pixaは無料で使えますか？', '無料で始められます。必要に応じてプランをアップグレードし、すべての機能にアクセスできます。'],
  ],
  cta: {
    heading: '複数のAIモデルにアクセスして比較',
    button: 'プレイグラウンドを起動',
  },
  newsletter: {
    heading: 'ニュースレターに登録',
    desc: '製品の知見とアップデートをお届けします。',
    placeholder: 'メールアドレス',
    cta: '登録',
  },
  footer: {
    columns: [
      ['リソース', ['はじめに', 'APIドキュメント', 'APIエンドポイント', '稼働状況', '料金']],
      ['会社', ['サポート', 'システム', 'ブログ', 'Twitter', 'LinkedIn']],
      ['法的情報', ['プライバシーポリシー', '利用規約', 'Cookieポリシー']],
    ],
    copyright: '© 2026 Pixa. 全著作権所有。',
  },
} as const
